# Generated by Django 3.1.12 on 2021-07-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210705_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=985999, unique=True),
        ),
    ]
